### PR TITLE
fix: update german translations

### PR DESCRIPTION
**Pull request by apollo79**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our guidelines: https://github.com/riccardoperra/codeimage/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x ] Other... Please describe: Update of i18n / german translations
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

The new translations are more fluid for german users

## Does this PR introduce a breaking change?

```
[ ] Yes
[x ] No
```

## Other information

Because some of the german words are very long, at least on my screen, some of the labels are partly hidden behind the related inputs / selects. What is the best way to avoid that? Should I insert some hyphens?

### CODE REVIEW

**Review by riccardoperra — APPROVED** [review]

**Comment by riccardoperra** [comment]
Thanks for the PR 😄

**Comment by apollo79** [comment]
Is there a good solution for the long words?

**Comment by riccardoperra** [comment]
Probably no, the `word-break` css property could help but It doesn't look good sometimes (for example when it breaks for just 1/2 words)

**Comment by apollo79** [comment]
Yes, that's true. But I found it looking better than if the words are partly hidden. Sadly `hyphens` is not well supported.

**Comment by riccardoperra** [comment]
> Yes, that's true. But I found it looking better than if the words are partly hidden. Sadly `hyphens` is not well supported.

Yes, this could be a good solution.

https://github.com/riccardoperra/codeimage/blob/ed9671c2f9e4c56f95e736397bb0cb14277166a7/apps/codeimage/src/components/PropertyEditor/EditorSidebar.css.ts#L81-L95

Didn't try but I think that the `display` should be `block` to get the ellipsis working so the vertical align center must be done also with `line-height`

Also, the padding could be adjusted as `10px` to get more space 
https://github.com/riccardoperra/codeimage/blob/ed9671c2f9e4c56f95e736397bb0cb14277166a7/apps/codeimage/src/components/PropertyEditor/EditorSidebar.css.ts#L89

You can open a new PR about that 😄

**Pull request merged**
