### PR TITLE
feat: added Cascadia Code font

### PR DESCRIPTION
**Pull request by max-programming**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/riccardoperra/codeimage/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by riccardoperra** [comment]
Hey @max-programming, thank you 😄

the PR is ok, CI is broken for these pr so is fine 

I will do a check on local environment just to be sure everything is ok then I’ll merge it and deploy

**Comment by max-programming** [comment]
> Everything is fine 😄 thank you. Will do a deploy later

Thanks! The dev env didn't quite work for me so I just made the changes.

**Comment by riccardoperra** [comment]
@max-programming just to know, what was the issue? I may have to update my CONTRIBUTORS.md file

**Comment by riccardoperra** [comment]
1.0.6 release with your changes is live 🙏

**Comment by max-programming** [comment]
Got this error when I ran `pnpm i`
```
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ pnpm-bundle-workspace-package 1.0.2
  └─┬ @pnpm/find-workspace-packages 4.0.43
    └─┬ @pnpm/cli-utils 0.7.43
      └─┬ @pnpm/config 15.10.12
        └─┬ @pnpm/pnpmfile 3.0.3
          └─┬ @pnpm/core 6.0.3
            └─┬ @pnpm/hooks.read-package-hook 1.0.2
              └─┬ @yarnpkg/extensions 2.0.0-rc.6
                └── ✕ missing peer @yarnpkg/core@^4.0.0-rc.24
Peer dependencies that should be installed:
  @yarnpkg/core@^4.0.0-rc.24

packages/highlight
└─┬ rollup-plugin-dts 5.0.0
  └── ✕ unmet peer rollup@^3.0.0: found 2.79.1

packages/ui
├─┬ @babel/plugin-syntax-jsx 7.18.6
│ └── ✕ missing peer @babel/core@^7.0.0-0
├─┬ @rollup/plugin-babel 6.0.0
│ └── ✕ missing peer @babel/core@^7.0.0
└─┬ acorn-jsx 5.3.2
  └── ✕ missing peer acorn@"^6.0.0 || ^7.0.0 || ^8.0.0"
Peer dependencies that should be installed:
  @babel/core@">=7.0.0 <8.0.0"        acorn@"^6.0.0 || ^7.0.0 || ^8.0.0"

hint: If you want peer dependencies to be automatically installed, add "auto-install-peers=true" to an .npmrc file at the root of your project.
hint: If you don't want pnpm to fail on peer dependency issues, add "strict-peer-dependencies=false" to an .npmrc file at the root of your project.
```

And this error when I ran `pnpm dev`
```
✘ [ERROR] [plugin externalize-deps] Failed to resolve entry for package "@codeimage/vanilla-extract". The package may have incorrect main/module/exports specified in its package.json.

    ../../node_modules/.pnpm/esbuild@0.15.11/node_modules/esbuild/lib/main.js:1327:27:
      1327 │         let result = await callback({
           ╵                            ^
```
Something might be wrong with my system. Large projects usually don't work

**Comment by riccardoperra** [comment]
Ok it’s the same I got while trying to playground with CodeSandbox

basically due to “strict-peer-dependencies” pnpm install fail, then the libs:build too because there is a package about prisma models that’s failing (you need docker and the containers probably)

I will update that workflow  in order to be able to run the project correctly 😉 thank you so much

**Pull request merged**
