### PR TITLE
Merge next in main

### PR DESCRIPTION
**Pull request by riccardoperra**
This branch contains some updates for the API rest
- [X] domain handler funtions #485 
- [X] domain error implementation #481  

### Breaking changes
-  Moving away from @solid-aria and using https://github.com/riccardoperra/codeui
-  Presets
-  Refactoring CI to be faster

Must be merged with:
- [x] #472 - #492
- [x] #482 
- [x] #520
- [x] #519
- [x] #518 
- [x] #517
- [x] #516
- [x] #515
- [x] #514 
- [x] #513 
- [x] #512 
- [x] #508 
- [ ] #509
- [x] #507
- [x] #506
- [x] #517
- [x] #516 
- [x] #515
- [x] #514
- [x] #513 
- [x] #512 
- [x] #508
- [x] #506
- [x] #504
- [ ] #503
- [x] #502 
- [x] #501
- [x] #500 
- [x] #499 
- [x] #498 
- [x] #497 
- [x] #496 
- [x] #494 
- [x] #492

### CODE REVIEW

**Review by hackpirodev — APPROVED** [review]

**Review by hackpirodev — APPROVED** [review]

**Comment by riccardoperra** [comment]
@hackpirodev We need to update the delete API in order to return an empty body instead of null

image
image

**Comment by riccardoperra** [comment]
@hackpirodev Currently the name property is mandatory and in both BE and FE side the empty string is allowed.

image

We should add a validation logic for backend using typebox and we have to display an error message on the dialog if it doesn't meet any criteria.

CodeUi is supporting the property validationState and errorMessage in order to show the content

https://codeui.netlify.app/text-input
image

**Comment by riccardoperra** [comment]
@hackpirodev I don't know why but seems that in the build files vite is removing the presets properties even they are present on the CI

image
image

currently there is no limits even if I set 5 for guest and 10 for loggedin users

**Comment by riccardoperra** [comment]
@hackpirodev rename action seems now broken, probably due to the refactor for both Dialog and RenameContentDialog component

https://user-images.githubusercontent.com/37072694/234764565-f0372390-03cf-48df-9c8b-6fdd719b8607.mp4

**Comment by riccardoperra** [comment]
On mobile iOS safari spaces could be broken, and the scrollbar seems to be under the card content
IMG_7652

**Comment by riccardoperra** [comment]
Select value binding for the syntax highlighting options are now broken 

IMG_7654

**Comment by riccardoperra** [comment]
CodeImage logo Text in light mode is still white
IMG_7655

**Comment by riccardoperra** [comment]
Opening the preset the first time will always trigger the “update flow” calling the API.

we should enter in that flow only after an user input change.

This could be a statebuilder/commands issue

https://user-images.githubusercontent.com/37072694/234765753-9903b05a-7029-464f-9f4b-3faf744ed2d4.mp4

**Comment by riccardoperra** [comment]
> Select value binding for the syntax highlighting options are now broken
> 
> 

fixed by https://github.com/riccardoperra/codeimage/pull/521

**Comment by riccardoperra** [comment]
> @hackpirodev I don't know why but seems that in the build files vite is removing the presets properties even they are present on the CI
> 
> image image
> 
> currently there is no limits even if I set 5 for guest and 10 for loggedin users

Seems fixed with latest deploy

**Pull request merged**
